modLoader="javafml"
loaderVersion="[47,)"
license="Creative Commons Attribution-NonCommercial 3.0"

[[mods]]
modId="lifestream_components"
version="1.0.2"
displayName="Lifestream Components"
displayURL="https://setacaie.tech"
logoFile="logo.png"
credits="Made with MCreator"
authors="setacaie"
description="A collection of components for use in the Lifestream modpack."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.lifestream_components]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.lifestream_components]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

